nginx_servers:
  - group: "example-group" # server group name
    servers:
      - name: "nginx-server-1" # server name
        host: "192.168.1.10" # server ip
        port: 22 
        user: "nginx" 
        auth:
          # Options: password, key
          method: "password"
          password: "your_password"
          # key_path: "/home/user/.ssh/id_rsa"
        nginx_config_dir: "/etc/nginx" # nginx config dir
        nginx_binary_path: "/usr/sbin/nginx" # nginx binary path
        check_dir: "/tmp/nginx_check" # check dir 
        # backup_dir: "/var/backups/nginx" # backup dir Not currently used
